name: AIPencil
options:
  bundleIdPrefix: com.aipencil
  deploymentTarget:
    iPad: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    TARGETED_DEVICE_FAMILY: 2
    SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

packages:
  SwiftAnthropic:
    url: https://github.com/jamesrochabrun/SwiftAnthropic
    from: "1.0.0"
  LaTeXSwiftUI:
    url: https://github.com/colinc86/LaTeXSwiftUI
    from: "1.5.0"

targets:
  AIPencil:
    type: application
    platform: iOS
    sources:
      - AIPencil
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_UISupportsDocumentBrowser: false
        TARGETED_DEVICE_FAMILY: 2
        PRODUCT_BUNDLE_IDENTIFIER: com.aipencil.AIPencil
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        SWIFT_EMIT_LOC_STRINGS: true
    dependencies:
      - package: SwiftAnthropic
      - package: LaTeXSwiftUI

  AIPencilTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - AIPencilTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.aipencil.AIPencilTests
    dependencies:
      - target: AIPencil
